### ISSUE TITLE
BOOOOOOOUUUUUUUUUYYYYYYYYAAAAHHHHH

### ISSUE THREAD

**Issue by loublh** [loublh/PROJET-ALGO#21]
[projetM1102.zip](https://github.com/loublh/PROJET-ALGO/files/714462/projetM1102.zip)

**Comment by ghost** [comment]
[versionClassique.zip](https://github.com/loublh/PROJET-ALGO/files/716006/versionClassique.zip)

**Comment by ghost** [comment]
[projetM1102.zip](https://github.com/loublh/PROJET-ALGO/files/716346/projetM1102.zip)
